<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="DESKTOP-O4OM8TU" failures="3" tests="7" name="tests.testng.TestNgSuiteRunner" time="0.194" errors="0" timestamp="2021-10-18T09:59:19 BRT" skipped="0">
  <testcase classname="tests.testng.TestNgSuiteRunner" name="runScenario" time="0.009"/>
  <system-out/>
  <testcase classname="tests.testng.TestNgSuiteRunner" name="runScenario" time="0.019">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at tests.testng.features.steps.Third.enterLogInData(Third.java:25)
at ✽.user enters the "Natan" and "12312" credentials(classpath:tests/testng/features/Third.feature:32)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="tests.testng.TestNgSuiteRunner" name="runScenario" time="0.017"/>
  <system-out/>
  <testcase classname="tests.testng.TestNgSuiteRunner" name="runScenario" time="0.009"/>
  <system-out/>
  <testcase classname="tests.testng.TestNgSuiteRunner" name="runScenario" time="0.011">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at tests.testng.features.steps.Third.enterLogInData(Third.java:25)
at ✽.user enters the "Natan" and "122312" credentials(classpath:tests/testng/features/Third.feature:32)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
  <testcase classname="tests.testng.TestNgSuiteRunner" name="runScenario" time="0.111"/>
  <system-out/>
  <testcase classname="tests.testng.TestNgSuiteRunner" name="runScenario" time="0.018">
    <failure message="expected [true] but found [false]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:99)
at org.testng.Assert.failNotEquals(Assert.java:1037)
at org.testng.Assert.assertTrue(Assert.java:45)
at org.testng.Assert.assertTrue(Assert.java:55)
at tests.testng.features.steps.Third.enterLogInData(Third.java:25)
at ✽.user enters the "Natan" and "1asdasd2" credentials(classpath:tests/testng/features/Third.feature:32)
]]>
    </failure>
  </testcase> <!-- runScenario -->
  <system-out/>
</testsuite> <!-- tests.testng.TestNgSuiteRunner -->
